version: '3.8'

services:
  clippy:
    build: ./clippy
    env_file: .env
    volumes:
      - ./storage/clippy:/storage
    networks:
      - clippy

  pytube-api:
    image: ewbrowntech/pytube-api:latest
    env_file: .env
    volumes:
      - ./storage/pytube-api:/storage
    networks:
      - clippy

networks:
  clippy:
    external: true
